"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Generator, Optional, Tuple, Type
from pydantic import BaseModel
from pydantic.fields import FieldInfo
from argdantic.parsing import ActionTracker, Argument

def format_description(description: Optional[str], has_default: bool, is_required: bool) -> str:
    """Formats the field description, adding additional info about defaults and if it is required.

    Args:
        description (str): The description.
        has_default (bool): If the field has a default value.
        is_required (bool): If the field is required.

    Returns:
        str: The formatted description.
    """
    ...

def argument_from_field(field_info: FieldInfo, kebab_name: str, delimiter: str, internal_delimiter: str, parent_path: Tuple[str, ...], custom_identifier: Optional[str] = ...) -> Argument:
    """Converts a pydantic field to a single argument.

    Args:
        field (Field): The field to convert.
        kebab_name (str): The kebab case name of the field.
        delimiter (str): The delimiter to use for the argument names.
        internal_delimiter (str): The delimiter to use for the internal names.
        parent_path (Tuple[str, ...]): The parent path of the field.

    Returns:
        Argument: The argument.
    """
    ...

def model_to_args(model: Type[BaseModel], delimiter: str, internal_delimiter: str, parent_path: Tuple[str, ...] = ...) -> Generator[Argument, None, None]:
    """Converts a pydantic model to a list of arguments.

    Args:
        model (Type[BaseModel]): The model to convert.
        delimiter (str): The delimiter to use for the argument names.
        internal_delimiter (str): The delimiter to use for the internal names.
        parent_path (Tuple[str, ...], optional): The parent path. Defaults to tuple().

    Returns:
        ArgumentParser: The argument parser.
    """
    ...

def args_to_dict_tree(kwargs: Dict[str, Any], internal_delimiter: str, remove_helpers: bool = ..., cli_trackers: Optional[Dict[str, ActionTracker]] = ...) -> Dict[str, Any]:
    """Transforms a flat dictionary of identifiers and values back into a complex object made of nested dictionaries.
    E.g. the following input: `animal__type='dog', animal__name='roger', animal__owner__name='Mark'`
    becomes: `{animal: {name: 'roger', type: 'dog'}, owner: {name: 'Mark'}}`

    Args:
        kwargs (Dict[str, Any]): flat dictionary of available fields
        internal_delimiter (str): delimiter required to split fields
        remove_helpers (bool, optional): whether to remove helper fields (e.g., __func__). Defaults to True.
        cli_trackers (Dict[str, ActionTracker], optional): dictionary of action trackers. Defaults to None.

    Returns:
        Dict[str, Any]: nested dictionary of properties to be converted into pydantic models
    """
    ...

