"""
This type stub file was generated by pyright.
"""

from argparse import ArgumentParser, Namespace
from typing import Any, Callable, Generic, Iterable, List, Optional, Type, TypeVar
from pydantic import BaseModel
from pydantic_settings import BaseSettings
from pydantic_settings.sources import PydanticBaseSettingsSource
from argdantic.parsing import Argument
from argdantic.stores import SettingsStoreCallable

SettingSourceCallable = Callable[[Type[BaseSettings]], PydanticBaseSettingsSource]
ParserType = TypeVar("ParserType", bound="ArgParser")
class Command:
    """
    A command represents a single function that can be invoked from the command line.
    It is composed of a callback function, a list of arguments, and a pydantic model
    that is used to validate the arguments.
    """
    def __init__(self, callback: Callable, arguments: Iterable[Argument], model_class: Type[BaseModel], name: str, description: Optional[str] = ..., singleton: bool = ..., stores: Optional[List[SettingsStoreCallable]] = ..., delimiter: str = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __call__(self, args: Namespace) -> Any:
        """
        Invoke the command with the arguments already parsed by argparse,
        and return the result, which is the return value of the callback.
        Arguments are converted into a dictionary and passed to the pydantic model
        for validation. The validated model is then passed to the callback.

        Args:
            args (Namespace): parsed arguments provided by argparse.

        Returns:
            Any: return value of the callback.
        """
        ...
    
    def build(self, parser: ArgumentParser) -> None:
        """
        Build the command by adding all arguments to the parser.

        Args:
            parser (ArgumentParser): parser to add the arguments to.
        """
        ...
    


class ArgParser(Generic[ParserType]):
    """
    A parser is a collection of commands and subparsers.
    It is responsible for building the entrypoint for the command line interface,
    and invoking the correct command by constructing the parser hierarchy.
    """
    def __init__(self, name: Optional[str] = ..., description: Optional[str] = ..., force_group: bool = ..., delimiter: str = ..., internal_delimiter: str = ..., subcommand_meta: str = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __call__(self, args: Optional[Namespace] = ...) -> Any:
        """
        Invoke the parser by building the entrypoint and parsing the arguments.
        The result is the return value of the callback of the invoked command.

        Args:
            args (Sequence[Any], optional): arguments to parse. Defaults to None.

        Returns:
            Any: return value of the callback.
        """
        ...
    
    def command(self, name: Optional[str] = ..., help: Optional[str] = ..., sources: Optional[List[SettingSourceCallable]] = ..., stores: Optional[List[SettingsStoreCallable]] = ..., singleton: bool = ...) -> Callable:
        """Decorator to register a function as a command.

        Args:
            name (str, optional): Name of the command. Defaults to the function name when not provided.
            help (str, optional): Help text for the command. Defaults to the function docstring when not provided.
            delimiter (str, optional): Custom delimiter character. Defaults to ".".
            internal_delimiter (str, optional): Custom internal delimiter. Defaults to "__".

        Returns:
            Callable: The same function, promoted to a command.
        """
        ...
    
    def add_parser(self, parser: ParserType, name: Optional[str] = ...) -> None:
        """
        Add a subparser to the current parser.

        Args:
            parser (ArgParser): subparser to add.
        """
        ...
    


