"""
This type stub file was generated by pyright.
"""

from collections.abc import MutableMapping
from typing import Any, Iterator

class Registry(MutableMapping):
    """Simple class registry for mapping types and their argument handlers."""
    def __init__(self) -> None:
        ...
    
    def __getitem__(self, key: type) -> Any:
        ...
    
    def __setitem__(self, key: type, value: Any) -> None:
        ...
    
    def __delitem__(self, key: type) -> None:
        ...
    
    def __iter__(self) -> Iterator[Any]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def get(self, key: type, default: Any = ...) -> Any:
        ...
    
    def register(self, *keys: Any): # -> Callable[..., Type[Any]]:
        ...
    


