"""
This type stub file was generated by pyright.
"""

from argparse import Namespace
from typing import Any, Optional
from argdantic import ArgParser

class Result:
    def __init__(self, return_value: Any, exception: Optional[Exception], exc_info: Optional[Any]) -> None:
        ...
    


class CLIRunner:
    def __init__(self, catch_exceptions: bool = ...) -> None:
        ...
    
    def invoke(self, cli: ArgParser, args: Optional[Namespace]) -> Any:
        ...
    


