"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Type

def type_name(field_type: Type[Any]) -> str:
    """Returns the name of the type, or the name of the type's origin, if the type is a
    typing construct.
    Args:
        field_type (type): pydantic field type
    Returns:
        str: name of the type
    """
    ...

def is_multiple(field_type: Type[Any]) -> bool:
    """Checks whether the current type is a container type ('contains' other types), like
    lists and tuples.
    Args:
        field_type (type): pydantic field type
    # Returns:
        bool: true if a container, false otherwise
    """
    ...

def is_mapping(field_type: Type[Any]) -> bool:
    """Checks whether this field represents a dictionary or JSON object.
    Args:
        field_type (type): pydantic type
    Returns:
        bool: true when the field is a dict-like object, false otherwise.
    """
    ...

def is_container(field_type: Type[Any]) -> bool:
    """Checks whether the current type is a container type ('contains' other types), like
    lists and tuples.
    Args:
        field_type (type): pydantic field type
    Returns:
        bool: true if a container, false otherwise
    """
    ...

def is_typing(field_type: Type[Any]) -> bool:
    """Checks whether the current type is a module-like type.
    Args:
        field_type (type): pydantic field type
    Returns:
        bool: true if the type is itself a type
    """
    ...

def is_optional(field_type: Optional[Type[Any]]) -> bool:
    """Checks whether the current type is an optional type.
    Args:
        field_type (type): pydantic field type
    Returns:
        bool: true if the type is optional, false otherwise
    """
    ...

def get_optional_type(field_type: Optional[Type[Any]]) -> Type[Any]:
    """Returns the type of the optional field.
    Args:
        field_type (type): pydantic field type
    Returns:
        Type[Any]: the type of the field
    """
    ...

