"""
This type stub file was generated by pyright.
"""

from argparse import Action, ArgumentParser, Namespace
from typing import Any, Optional, Sequence, Union

class StoreAction(Action):
    """
    Store action for argparse. This class is used to store the value of an argument.
    This thin wrapper around the argparse Action is used to track if a field has been explicitly set or not.
    """
    def __init__(self, option_strings: Sequence[str], dest: str, nargs: Optional[Union[int, str]] = ..., **kwargs) -> None:
        ...
    
    def __call__(self, parser: ArgumentParser, namespace: Namespace, values: Optional[Union[Sequence[Any], str]], option_string: Optional[str] = ...) -> None:
        ...
    
    @property
    def specified(self) -> bool:
        ...
    


class StoreConstAction(StoreAction):
    def __init__(self, option_strings: Sequence[str], dest: str, const: Any, nargs: Union[int, str] = ..., **kwargs: dict) -> None:
        ...
    
    def __call__(self, parser: ArgumentParser, namespace: Namespace, values: Optional[Union[Sequence[Any], str]], option_string: Optional[str] = ...) -> None:
        ...
    


class StoreTrueAction(StoreConstAction):
    def __init__(self, option_strings: Sequence[str], dest: str, **kwargs: Any) -> None:
        ...
    


class StoreFalseAction(StoreConstAction):
    def __init__(self, option_strings: Sequence[str], dest: str, **kwargs: Any) -> None:
        ...
    


class AppendAction(StoreAction):
    def __init__(self, option_strings: Sequence[str], dest: str, nargs: Optional[Union[int, str]], const: Optional[Any] = ..., **kargs: dict) -> None:
        ...
    
    def __call__(self, parser: ArgumentParser, namespace: Namespace, values: Optional[Union[str, Sequence[Any]]], option_string: Optional[str] = ...) -> None:
        ...
    


