"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from argparse import ArgumentParser
from collections import abc, deque
from enum import Enum
from typing import Any, Dict, Iterator, List, Literal, Mapping, Optional, Sequence, Tuple, Type
from argdantic.parsing.actions import Action

registry = ...
cli_types: Dict[str, Tuple[Any, str]] = ...
cli_default = ...
class ActionTracker:
    """
    Action tracker for argparse actions. This class is used to track if an action has been
    specified or not. This is useful for determining if an argument has been set or not using the CLI.
    """
    def __init__(self, action_class: Type[Action]) -> None:
        ...
    
    def __call__(self, option_strings: Sequence[str], dest: str, **kwargs) -> Any:
        ...
    
    def is_set(self) -> bool:
        ...
    


class MultiActionTracker(ActionTracker):
    """
    Multi action tracker for argparse actions. This class is used to track if an action has been
    specified or not. Compared to the ActionTracker, this class is used for actions that can be
    specified multiple times.
    """
    def __init__(self, trackers: List[ActionTracker]) -> None:
        ...
    
    def is_set(self) -> bool:
        ...
    


class Argument(ABC):
    """
    Base class for all argument types. This class is not meant to be used directly, but rather
    subclassed to create new argument types.
    """
    def __init__(self, *field_names: str, identifier: str, field_type: Type[Any], default: Any = ..., required: bool = ..., description: Optional[str] = ...) -> None:
        ...
    
    @abstractmethod
    def build(self, parser: ArgumentParser) -> ActionTracker:
        ...
    
    def build_internal(self, parser: ArgumentParser, *, action: Type[Action], **optional_fields: Any) -> ActionTracker:
        ...
    


class PrimitiveArgument(Argument):
    """
    Argument for primitive types, assigned as default argument type
    """
    def build(self, parser: ArgumentParser) -> ActionTracker:
        ...
    


@registry.register(bool)
class FlagArgument(Argument):
    """
    Argument for a boolean flag. If the flag is present, the value is True, otherwise False
    """
    def build(self, parser: ArgumentParser) -> ActionTracker:
        ...
    


@registry.register(list, tuple, set, frozenset, range, deque, abc.Sequence, abc.Iterable)
class MultipleArgument(Argument):
    """
    Argument that accepts multiple values.
    When the field type is a container, the inner type is used to determine the type of the argument.
    For example, a field type of List[int] will result in an argument that accepts multiple integers.
    """
    def build(self, parser: ArgumentParser) -> ActionTracker:
        ...
    


@registry.register(Literal, Enum)
class ChoiceArgument(Argument):
    """
    ChoiceArgument is a special case of MultipleArgument that has a fixed number of choices.
    It supports both Enum and Literal types. Overriding the *contains* and *iter* methods allows
    to use the very same class as a custom choices argument for argparse.
    """
    def __contains__(self, item: Any) -> bool:
        ...
    
    def __iter__(self) -> Iterator:
        ...
    
    def __next__(self) -> Any:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def convert(self, name: Any) -> Any:
        ...
    
    def build(self, parser: ArgumentParser) -> ActionTracker:
        ...
    


@registry.register(dict, Dict, Mapping)
class DictArgument(Argument):
    """
    Argument for a dictionary type. The value is a JSON string.
    """
    def build(self, parser: ArgumentParser) -> ActionTracker:
        ...
    


