"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Callable, Literal, Optional, Set, Union
from pydantic import BaseModel
from pydantic_settings import BaseSettings

SettingsStoreCallable = Callable[[Union[BaseSettings, BaseModel]], None]
class BaseSettingsStore(ABC):
    """
    A settings store is a callable object that takes an input file path
    and stores settings to it in a specific format, given by the implementation.
    """
    def __init__(self, path: Union[str, Path], *, mode: Literal["python", "json"] = ..., encoding: str = ..., include: Optional[Set[str]] = ..., exclude: Optional[Set[str]] = ..., by_alias: bool = ..., exclude_unset: bool = ..., exclude_defaults: bool = ..., exclude_none: bool = ...) -> None:
        ...
    
    @abstractmethod
    def __call__(self, settings: BaseSettings) -> None:
        ...
    


