"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional, Set, Union
from pydantic_settings import BaseSettings
from argdantic.stores.base import BaseSettingsStore

class JsonSettingsStore(BaseSettingsStore):
    """
    A JSON file settings store writes settings to a JSON file.
    Orjson is used if available, otherwise the standard json module is used.
    """
    def __init__(self, path: Union[str, Path], *, encoding: str = ..., include: Optional[Set[str]] = ..., exclude: Optional[Set[str]] = ..., by_alias: bool = ..., exclude_unset: bool = ..., exclude_defaults: bool = ..., exclude_none: bool = ...) -> None:
        ...
    
    def __call__(self, settings: BaseSettings) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


