"""
This type stub file was generated by pyright.
"""

from pydantic_settings import BaseSettings
from argdantic.stores.base import BaseSettingsStore

class TomlSettingsStore(BaseSettingsStore):
    """
    A TOML file settings store writes settings to a TOML file.
    Tomli is used if available, otherwise the standard toml module is used.
    """
    def __call__(self, settings: BaseSettings) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


