"""
This type stub file was generated by pyright.
"""

from pydantic_settings import BaseSettings
from argdantic.stores.base import BaseSettingsStore

class YamlSettingsStore(BaseSettingsStore):
    """
    A YAML file settings store writes settings to a YAML file.
    PyYAML is used if available, otherwise the standard yaml module is used.
    """
    def __call__(self, settings: BaseSettings) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


