"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Optional, Type, Union
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource
from pydantic_settings.sources import DotEnvSettingsSource as PydanticEnvSource, DotenvType

class SettingsSourceBuilder(ABC):
    """
    An argdantic source is a callable object that takes an input settings object
    and returns an actual source, required to postpone the init of default sources.
    """
    @abstractmethod
    def __call__(self, settings_cls: Type[BaseSettings]) -> PydanticBaseSettingsSource:
        ...
    


class FileSettingsSourceBuilder(SettingsSourceBuilder):
    """
    A file source builder is a callable object that takes an input file path
    to read settings from, and returns an instance of settings source that
    can be used to populate to a pydantic model.
    """
    def __init__(self, path: Union[str, Path]) -> None:
        ...
    


class FileBaseSettingsSource(PydanticBaseSettingsSource):
    """
    Abstract settings source that expects an extra path, together with the settings class.
    """
    def __init__(self, settings_cls: Type[BaseSettings], path: Union[str, Path]) -> None:
        ...
    


class PydanticMultiEnvSource(PydanticEnvSource):
    """
    A pydantic settings source that loads settings from multiple environment sources.
    This loads from both the environment variables and the dotenv file.
    """
    ...


class EnvSettingsSource(SettingsSourceBuilder):
    """
    Reads settings from environment variables.
    This class inherits from the pydantic EnvSettingsSource class to fully customize input sources.
    """
    def __init__(self, env_file: Optional[DotenvType], env_file_encoding: Optional[str] = ..., env_nested_delimiter: Optional[str] = ..., env_prefix: str = ..., env_case_sensitive: bool = ...) -> None:
        ...
    
    def __call__(self, settings_cls: Type[BaseSettings]) -> PydanticBaseSettingsSource:
        ...
    


class SecretsSettingsSource(SettingsSourceBuilder):
    """Reads secrets from the given directory.
    This class inherits from the pydantic SecretsSettingsSource class to fully customize input sources.
    """
    def __init__(self, secrets_dir: Optional[Union[str, Path]], case_sensitive: bool = ..., env_prefix: str = ...) -> None:
        ...
    
    def __call__(self, settings_cls: Type[BaseSettings]) -> PydanticBaseSettingsSource:
        ...
    


