"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Tuple, Type
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource
from argdantic.sources.base import FileBaseSettingsSource

DEFAULT_SOURCE_FIELD = ...
class DynamicFileSource(PydanticBaseSettingsSource):
    """
    Source class for loading values provided during settings class initialization.
    """
    def __init__(self, settings_cls: Type[BaseSettings], source_cls: Type[FileBaseSettingsSource], init_kwargs: Dict[str, Any], required: bool, field_name: Optional[str] = ...) -> None:
        ...
    
    def get_field_value(self, field: Any, field_name: str) -> Tuple[Any, str, bool]:
        ...
    
    def __call__(self) -> Dict[str, Any]:
        ...
    
    def __repr__(self) -> str:
        ...
    


def from_file(loader: Type[FileBaseSettingsSource], use_field: Optional[str] = ..., required: bool = ...): # -> Callable[..., type[DynamicSourceSettings]]:
    ...

