"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Tuple, Type
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource
from argdantic.sources.base import FileBaseSettingsSource, FileSettingsSourceBuilder

class JsonFileLoader(FileBaseSettingsSource):
    """
    Class internal to pydantic-settings that reads settings from a JSON file.
    This gets spawned by the JsonSettingsSource class.
    """
    def get_field_value(self, field: FieldInfo, field_name: str) -> Tuple[Any, str, bool]:
        ...
    
    def __call__(self) -> Dict[str, Any]:
        ...
    


class JsonSettingsSource(FileSettingsSourceBuilder):
    """
    A JSON file settings source reads settings from a JSON file.
    Orjson is used if available, otherwise the standard json module is used.
    """
    def __call__(self, settings: Type[BaseSettings]) -> PydanticBaseSettingsSource:
        ...
    
    def __repr__(self) -> str:
        ...
    


