"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Tuple, Type
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource
from argdantic.sources.base import FileBaseSettingsSource, FileSettingsSourceBuilder

class TomlFileLoader(FileBaseSettingsSource):
    """
    Class internal to pydantic-settings that reads settings from a TOML file.
    This gets spawned by the TomlSettingsSource class.
    """
    def get_field_value(self, field: FieldInfo, field_name: str) -> Tuple[Any, str, bool]:
        ...
    
    def __call__(self) -> Dict[str, Any]:
        ...
    


class TomlSettingsSource(FileSettingsSourceBuilder):
    """
    A TOML file settings source reads settings from a TOML file.
    """
    def __call__(self, settings: Type[BaseSettings]) -> PydanticBaseSettingsSource:
        ...
    
    def __repr__(self) -> str:
        ...
    


