"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Tuple, Type
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource
from argdantic.sources.base import FileBaseSettingsSource, FileSettingsSourceBuilder

class YamlFileLoader(FileBaseSettingsSource):
    """
    Class internal to pydantic-settings that reads settings from a YAML file.
    This gets spawned by the YamlSettingsSource class.
    """
    def get_field_value(self, field: FieldInfo, field_name: str) -> Tuple[Any, str, bool]:
        ...
    
    def __call__(self) -> Dict[str, Any]:
        ...
    


class YamlSettingsSource(FileSettingsSourceBuilder):
    """
    A YAML file settings source reads settings from a YAML file.
    If the PyYAML library is not installed, an error is raised.
    """
    def __call__(self, settings_cls: Type[BaseSettings]) -> PydanticBaseSettingsSource:
        ...
    
    def __repr__(self) -> str:
        ...
    


